from enum import Enum, auto


class Class(Enum):
    PLUS = auto()
    MINUS = auto()
    STAR = auto()
    FWDSLASH = auto()

    OR = auto()
    AND = auto()
    NOT = auto()
    XOR = auto()

    EQ = auto()
    EQSIGN = auto()
    NEQ = auto()
    LT = auto()
    GT = auto()
    LTE = auto()
    GTE = auto()

    LPAREN = auto()
    RPAREN = auto()
    LBRACKET = auto()
    RBRACKET = auto()
    LBRACE = auto()
    RBRACE = auto()

    ASSIGN = auto()
    SEMICOLON = auto()
    COMMA = auto()
    DOT = auto()
    COLON = auto()

    TYPE = auto()
    INT = auto()
    CHAR = auto()
    STRING = auto()
    VAR = auto()
    REAL = auto()
    BOOLEAN = auto()

    IF = auto()
    ELSE = auto()
    WHILE = auto()
    FOR = auto()
    BEGIN = auto()
    END = auto()
    PROCEDURE = auto()
    FUNCTION = auto()
    DO = auto()
    TO = auto()
    DOWNTO = auto()
    PROGRAM = auto()
    ARRAY = auto()
    OF = auto()
    THEN = auto()
    EXIT = auto()
    MOD = auto()
    DIV = auto()
    CASE = auto()
    CONST = auto()
    IN = auto()
    NIL = auto()
    REPEAT = auto()
    UNTIL = auto()

    BREAK = auto()
    CONTINUE = auto()
    RETURN = auto()

    ID = auto()
    EOF = auto()
